=== ChrisJeamme/X18A/chat.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT chat (message*)>
<!ATTLIST chat
	evenementId CDATA #REQUIRED
>
<!ELEMENT message (date,auteur,texte)>
<!ATTLIST message
	id CDATA #REQUIRED
>
<!ELEMENT date (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT texte (#PCDATA)>

=== ChrisJeamme/X18A/chat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chat SYSTEM "chat.dtd">
<chat evenementId="1">
    <message idUtilisateur="1" idEvenement="1">
    <date>2017</date>
    <auteur>Chris</auteur>
    <texte>Salut</texte>
    </message>
    <message idUtilisateur="2" idEvenement="1">
    <date>2018</date>
    <auteur>Jacquie</auteur>
    <texte>Salut</texte>
    </message>
</chat>
